Restore Visit toggling data-turbo-preview behavior
hotwired/turbo pull request #162
Opened 2021-02-06 20:48 UTC by seanpdoyle

Closes https://github.com/hotwired/turbo/issues/117
Closes https://github.com/hotwired/turbo/issues/159

---

When restoring from a cached snapshot, pass along the `isPreview` flag
to `View.renderPage`.

Also, always issue the request within `Visit.issueRequest`, since
process of restoring the cached preview is initiated prior to the
request intended to re-fetch the cached content.

2021-02-06 20:52 UTC, seanpdoyle commented on src/tests/functional/visit_tests.ts
> +    this.assert.equal(await this.nextAttributeMutationNamed("document", "data-turbo-preview"), "", "sets [data-turbo-preview] on the <html> element")
I'm not sure how, but this is causing StaleReference errors that are failing the suite: https://github.com/hotwired/turbo/pull/162/checks?check_run_id=1846330642#step:7:178

2021-02-09 21:00 UTC, seanpdoyle commented
The implementation change portion of this PR overlapped with the fix that https://github.com/hotwired/turbo/pull/169/ introduced. It's still valuable to ship this PR to add test coverage for this behavior.

2021-04-08 22:54 UTC, sstephenson requested changes
Mind rewording the commit message to indicate it's now just adding test coverage?

2021-04-09 01:54 UTC, merged

2021-04-09 01:55 UTC, sstephenson commented
Thank you!

2021-04-09 01:59 UTC, seanpdoyle commented
@sstephenson I think CI was failing. I'm investigating locally.