Fix navigation via links contained in shadown dom trees (WIP)
hotwired/turbo pull request #271
Opened 2021-05-23 13:47 UTC by ximus

[Current click handling logic](https://github.com/hotwired/turbo/blob/aae03ada8be4b46899330364d712cc1ae57f2400/src/observers/link_click_observer.ts#L62) will search up the DOM tree starting from
the `MouseEvent.target` element for an `a[href]` link element. With
this element present, Turbo can take over navigation from the browser.

However when such a link element finds itself contained within a
shadow DOM tree, browsers will set the `MouseEvent.target` to be
the shadow DOM's parent. This parent is above the link element
and hence Turbo will assume no link was clicked, will stand down
the browser's default navigation behavior will take over, leading
to a full page navigation.

Using `MouseEvent.composedPath()` allows reaching the 'real' target
of the click.

Here I implement a fix using `composedPath()`. It fixes my app where my buttons and links are encapsulated inside custom elements using shadow DOMs. Seems to work for me.

Writing a test however has been a challenge and **this PR cannot currently be merged**. Please see comments inline.

2021-05-23 13:49 UTC, ximus commented on src/observers/link_click_observer.ts
> +    console.log("fixed target is: ", event.composedPath()[0])
when click is triggered by a natural user click in the browser's GUI, this outputs:
<img width="1162" alt="Screen Shot 2021-05-23 at 15 03 27" src="https://user-images.githubusercontent.com/48771/119263187-53eb5e80-bbde-11eb-8c41-864eb174af8e.png">

when the lick is triggered using the WIP test case initially submitted in this PR, this outputs:
<img width="843" alt="Screen Shot 2021-05-23 at 15 02 22" src="https://user-images.githubusercontent.com/48771/119263225-6fef0000-bbde-11eb-87d9-f722893f76fa.png">

both in chrome and firefox

2021-08-23 10:51 UTC, kirillplatonov requested changes
@ximus it looks good! 👍 
I added few suggestions and fixed the test. Could you please clean up the PR and resolve merge conflicts?

2021-08-23 10:51 UTC, kirillplatonov commented on src/observers/link_click_observer.ts
> +      const target = event.composedPath()[0]
```suggestion
      const target = (event.composedPath && event.composedPath()[0]) || event.target
```
Having a fallback for unsupported browsers would be nice.

2021-08-23 10:51 UTC, kirillplatonov commented on src/tests/fixtures/navigation.html
> +      <p><custom-link-element id="same-origin-unannotated-custom-element-link" link="/src/tests/fixtures/one.html" text="Same-origin unannotated custom element link"></custom-link-element></p>
```suggestion
      <p><custom-link-element id="custom-link-element" link="/src/tests/fixtures/one.html" text="Same-origin unannotated custom element link"></custom-link-element></p>
```

2021-08-23 10:51 UTC, kirillplatonov commented on src/tests/functional/navigation_tests.ts
> +
```suggestion
  async "test following a same-origin unannotated custom element link"() {
    await this.nextBeat
    await this.remote.execute(() => {
      const shadowRoot = document.querySelector("#custom-link-element")?.shadowRoot
      const link = shadowRoot?.querySelector("a")
      link?.click()
    })
    await this.nextBody

    this.assert.equal(await this.pathname, "/src/tests/fixtures/one.html")
    this.assert.equal(await this.visitAction, "advance")
  }

```

This workaround will work.

2021-08-24 13:31 UTC, dhh commented
Fixed via #351

2021-08-24 13:31 UTC, closed without merging