Fix turbo stream link setting the src of a turbo frame container
hotwired/turbo pull request #968
Opened 2023-09-05 13:07 UTC by BakiVernes

There is a bug that exists when using a turbo stream link inside a turbo frame. The link click sets the src of the turbo frame element. When navigating browser history turbo saves the state of the src but fails to fetch it since the src is used for the turbo stream response. Example below on a new rails 7 app:

![Rails 7 app new](https://github.com/hotwired/turbo/assets/31761693/b07607b0-7167-48e1-b713-290b6d31959d)

This PR checks for the `data-turbo-stream` attribute and won't set the src of the frame element.

2023-09-11 22:06 UTC, BakiVernes commented
I have rebased this PR after the Typescript changes and would love some feedback. This bug has been a pain in our production app for some time now.

2023-09-12 16:50 UTC, BakiVernes commented
Might need a rerun on this. My tests are green.

2023-09-12 18:06 UTC, shiftyp commented on src/tests/functional/frame_tests.js
> +  await page.goto("/src/tests/fixtures/form.html")
Unknown if this relates to the test failures, but I think this is already done in the beforeEach hook

2023-09-12 18:07 UTC, shiftyp commented on src/tests/functional/frame_tests.js
> +  await page.goto("/src/tests/fixtures/form.html")
NVM, frames vs forms 🤦🏻

2023-09-13 10:15 UTC, afcapel requested changes
I think the test failures are legit, I can reproduce them locally too.

See my comment about the conditional in `willFollowLinkToLocation` for a possible solution.

2023-09-13 12:10 UTC, BakiVernes commented
@afcapel I have made the suggested changes, good catch.

What I am unsure about is the tests. I checked out the main branch and the tests are failing locally for me. Checked out the last couple of commits. The latest commit on which all test are green is https://github.com/hotwired/turbo/commit/4c006dc35e552f8b8feb2fb950ec8139c04ea781

2023-09-13 12:18 UTC, BakiVernes commented
> @afcapel I have made the suggested changes, good catch.
> 
> What I am unsure about is the tests. I checked out the main branch and the tests are failing locally for me. Checked out the last couple of commits. The latest commit on which all test are green is [4c006dc](https://github.com/hotwired/turbo/commit/4c006dc35e552f8b8feb2fb950ec8139c04ea781)

Nevermind 😅, the tests passed 🤷‍♀️

2023-09-13 12:51 UTC, merged