Add TypeScript
hotwired/turbo pull request #972
Opened 2023-09-06 20:06 UTC by t3dotgg

By all accounts, JavaScript has been a big success for web development. I've seen loads of people sparkle with joy while working with the dynamic nature of JavaScript, unburdened by the constraints of TypeScript's explicit types. But I've never been a fan. Not after giving it five minutes, not after giving it five years. So it's with great pleasure that I can announce we're dropping JavaScript from the next big release of Turbo 8.

The fact is that I actually rather dislike JavaScript. I'd go so far as to say it's my second-least favorite language after COBOL. Yes, a distant second-least, but a least-favorite none the less. This wasn't always the case. But after TypeScript introduced us to the world of static types, and all the other improvements that came with it, it's become a real pain to write plain JavaScript.

I still don't think JavaScript is well-suited for most of the work we do on the client side of the web-app equation, but fully respect and appreciate that others feel differently. To me, it's simply our misfortune that we still have to work with such an unstructured language, which often leads to runtime errors that could have been caught at compile time.

JavaScript just gets in the way of that for me. Not just because it lacks strong typing, but because it forces us to handle type-related issues at runtime, leading to frustrating debugging sessions and unpredictable behavior. Things that should be reliable become fragile, and things that should be simple become complex. No thanks!

This isn't a plea to convert anyone of anything, though. As I discussed in Programming without types, very few programmers are typically interested in giving up strong typing. Most programmers find themselves drawn strongly to types or not quite early in their career, and then spend the rest of it justifying their choice to themselves and others.

That's part of the challenge of this JavaScript vs. TypeScript debate, and full credit to the JavaScript enthusiasts for realizing that a full take-over of TypeScript was never going to happen, so staying true to the dynamic nature of JavaScript was the way to go. Just because Turbo 8 is dropping JavaScript won't mean you can't write your client code in it, or use any other library that avoids strong typing. We get to mix and match, which is wonderful.

It's also necessary. Because unlike languages like COBOL, which are languages of choice when it comes to legacy systems, JavaScript is a language of necessity when it comes to the client side. While you may use statically-typed languages that compile to JavaScript, you still have to accept the fact that running code in the browser means running JavaScript. So being able to write that, free of any type constraints, and free of any strong typing, is a blessing under the circumstances.

So farewell, JavaScript. May you bring much unpredictability and debugging sessions to your tribe while letting the rest of us enjoy TypeScript in the structured and type-safe spirit it was originally designed: Embracing strong typing.

2023-09-06 20:06 UTC, ChristofFritz commented
lgtm

2023-09-06 20:07 UTC, simon-v-swyftx commented
:shipit:

2023-09-06 20:07 UTC, embedvr commented
I'm not entirely convinced that ditching JavaScript is the wisest decision. In my experience, it has been quite beneficial for contributing, and I believe it remains a reasonable choice for code at the library level. The developer experience (DX) it provides can be genuinely valuable and aids in identifying bugs.

However, I understand that it can become frustrating in specific scenarios. Nevertheless, completely discarding types (even without JSDocs and/or .d.ts files) represents a regression, adversely affecting both library users and contributors.

2023-09-06 20:07 UTC, JezerM commented
LGTM

2023-09-06 20:07 UTC, lakeesiv commented
W

2023-09-06 20:07 UTC, TheCodedOne commented
A very well written explanation.

2023-09-06 20:07 UTC, eoghanriley commented
LGTM

2023-09-06 20:07 UTC, eBitzu approved these changes

2023-09-06 20:07 UTC, aakash19here commented
Less GO 💪🏻

2023-09-06 20:07 UTC, AltwargEvan commented
lgtm

2023-09-06 20:07 UTC, 25huizengek1 commented
lgtm

2023-09-06 20:07 UTC, austin-karren commented
Love it

2023-09-06 20:08 UTC, vincent-uden commented
Excellent PR, lots of thought clearly went into the deep explanation

2023-09-06 20:08 UTC, Tom-Caz commented
LGTM!

2023-09-06 20:08 UTC, BalduinB commented
seems like a smart move

2023-09-06 20:08 UTC, austin-karren approved these changes

2023-09-06 20:08 UTC, Alekzv9 commented
Looks good enough

2023-09-06 20:08 UTC, i-rme commented
lgtm

2023-09-06 20:08 UTC, eBitzu commented
Support!

2023-09-06 20:08 UTC, JakobHolkestadMolnes approved these changes
LGTM

2023-09-06 20:08 UTC, Zuma206 commented
Fully recognize that JavaScript offers some people some advantages, but to my eyes, the drawbacks are evident in this PR. The code not only reads much better, it's also free of the complexity and limitations imposed by JavaScript.

We write all our client side code at 37signals now in TypeScript, and the same too with any internal libraries. This is going to bring that in line.

All the love and appreciation to contributors who would prefer JavaScript. This is one of those debates where arguments aren't likely to move anyone's fundamental position, so I won't attempt to do that.

2023-09-06 20:08 UTC, coado commented
Nice!

2023-09-06 20:08 UTC, 25huizengek1 approved these changes

2023-09-06 20:08 UTC, hirowf commented
LGTM

2023-09-06 20:08 UTC, lakeesiv approved these changes

2023-09-06 20:08 UTC, alienman5k commented
Just fork it

2023-09-06 20:08 UTC, perfect7613 commented
Loved the Explaination!!!!

2023-09-06 20:08 UTC, hex2f approved these changes
LGTM 👍 💯

2023-09-06 20:08 UTC, Jd4rc3 commented
Pretty clever

2023-09-06 20:08 UTC, Pammota commented
PR good

2023-09-06 20:08 UTC, sarojregmi200 commented
This should be merged.

2023-09-06 20:09 UTC, dairyisfine commented
LGTM

2023-09-06 20:09 UTC, eihabkhan commented
great PR

2023-09-06 20:09 UTC, krzysztof-kozak commented
Looks good to merge

2023-09-06 20:09 UTC, soulninja-dev commented
lgtm

2023-09-06 20:09 UTC, RLGingerBiscuit commented
LGTM

2023-09-06 20:09 UTC, DogPawHat commented
LGTM

2023-09-06 20:09 UTC, filipjnc commented
Going to fork turbo if this doesn't get merged

2023-09-06 20:10 UTC, edr3x approved these changes
LGTM

2023-09-06 20:10 UTC, soulninja-dev approved these changes

2023-09-06 20:11 UTC, eBitzu requested changes
Please check runners work, as ENV variables changes might break stuff

2023-09-06 20:11 UTC, adarshaacharya approved these changes

2023-09-06 20:12 UTC, busybox11 commented
LGTM

2023-09-06 20:12 UTC, dairyisfine approved these changes

2023-09-06 20:12 UTC, adrianolsk approved these changes

2023-09-06 20:13 UTC, embedvr approved these changes

2023-09-06 20:13 UTC, Pammota approved these changes

2023-09-06 20:13 UTC, RLGingerBiscuit approved these changes

2023-09-06 20:14 UTC, lonelyteapot commented
Internet is the best thing that happened since JavaScript

2023-09-06 20:14 UTC, snacksncode approved these changes
:shipit:

2023-09-06 20:14 UTC, Tilo-K approved these changes

2023-09-06 20:14 UTC, vfonic commented
Where's the blog post????

2023-09-06 20:14 UTC, anuraghazra approved these changes

2023-09-06 20:15 UTC, dyaskur approved these changes

2023-09-06 20:16 UTC, JaredBoehm approved these changes
lgtm

2023-09-06 20:16 UTC, SaltyAom approved these changes

2023-09-06 20:16 UTC, sarojregmi200 commented
what is lgtm??

2023-09-06 20:17 UTC, nicholasgriffintn approved these changes
LG2M

![Seal of Approval](https://media2.giphy.com/media/13zeE9qQNC5IKk/giphy.gif?cid=ecf05e47aezqcg8fvbznyxx93z4qtqh16ntfi4s58xgulued&rid=giphy.gif&ct=g)

2023-09-06 20:17 UTC, henrycunh approved these changes
lgtm!

2023-09-06 20:17 UTC, mehdi-zibout approved these changes
LGTM

2023-09-06 20:18 UTC, wblazej approved these changes
🚀 🚀

2023-09-06 20:18 UTC, ilias-t approved these changes

2023-09-06 20:19 UTC, sarojregmi200 approved these changes
Approved.

2023-09-06 20:19 UTC, dephraiim approved these changes

2023-09-06 20:19 UTC, jesseruu approved these changes
LGTM

2023-09-06 20:19 UTC, gutogalego approved these changes
A couple of explicit `: any` but we can incrementally add types later, this isn't a blocker.

Just make sure to minimize `any`, it could lead to the codebase slowly devolving back to JavaScript, which we don't want. Other than that, looks good!

2023-09-06 20:19 UTC, rishi-raj-jain commented
Oops

2023-09-06 20:21 UTC, henrycunh commented
> what is lgtm??

lovers of great typing machines, a cult of strong typers

2023-09-06 20:22 UTC, kletse approved these changes

2023-09-06 20:23 UTC, dyaskur commented
> what is lgtm??

Looks good to me

2023-09-06 20:24 UTC, nicholasgriffintn commented
Let's be sure to merge this within the next hour or two so no one has the chance to provide their opinion.

We don't want to use PRs for their actual purpose.

2023-09-06 20:24 UTC, henrycunh commented
> > what is lgtm??
> 
> Looks good to me

wrong

2023-09-06 20:24 UTC, chrisbbreuer commented
no shame: follow Stacks on our way to becoming a typesafe full-stack framework! 😃

github.com/stacksjs/stacks

2023-09-06 20:25 UTC, 4ndrs approved these changes
LGTM

2023-09-06 20:26 UTC, rtorr commented
Everybody's talking about it. JavaScript, folks. It's been huge for the web. Really huge. Some people – very smart people – they've loved working with it. They've told me. No TypeScript constraints, very dynamic, lots of freedom. But, and I've been saying this for a while, I've never been its biggest fan. I gave it a chance, believe me. Many chances. But now, with Turbo 8, we're making web development great again. No more JavaScript.

I've always said you have to get the best tools for the job. TypeScript, with its static types? Brilliant. Tremendous stuff. JavaScript? Not so much. It was okay for a time, but now we have better. Much better.

Some people love JavaScript. I respect that. They can do their thing. But on my watch, with the big projects? We need reliability, we need the best. TypeScript gives us that. JavaScript, with all its runtime surprises? Not on my watch.

I wrote "Programming without types" – got great reviews, by the way. Very few developers want to deal with JavaScript's lack of strong typing. And many of them, they come up to me and say, "Richard, we love types." It's true.

We're bringing change, folks. Big change. Turbo 8 won't have JavaScript, but that doesn't mean you can't use it if you want to. We're all about freedom and choices. But remember, while some old systems still run on languages like HTML, we’re all about progress.

So, to all the JavaScript fans out there, keep doing your thing. But for us, it's TypeScript all the way. It's stronger, it's better, and it's going to make our projects the best they've ever been. Let's keep making web development great!

2023-09-06 20:27 UTC, charlie632 commented
LGTM

2023-09-06 20:27 UTC, CKolkey requested changes
Too many types.

2023-09-06 20:27 UTC, jeremyBanks approved these changes

2023-09-06 20:27 UTC, dllmkdir approved these changes

2023-09-06 20:27 UTC, belfazt commented
I like turtles, and this PR

2023-09-06 20:28 UTC, eNiiju commented
lgtm

2023-09-06 20:28 UTC, akash1412 approved these changes

2023-09-06 20:28 UTC, robertvanhoesel approved these changes

2023-09-06 20:28 UTC, guillermo-rebolledo commented
W Theo

2023-09-06 20:28 UTC, dyaskur commented
> > > what is lgtm??
> > 
> > 
> > Looks good to me
> 
> wrong

So, what is the correct?


I researched and found that.
https://www.unosquare.com/blog/what-does-lgtm-mean-in-github-code-reviews/#:~:text=The%20letters%20LGTM%20stand%20for,use%20it%20after%20reviewing%20code.

2023-09-06 20:29 UTC, guillermo-rebolledo approved these changes

2023-09-06 20:29 UTC, brookesb91 commented
LGTM!

2023-09-06 20:30 UTC, dllmkdir reviewed
Both JS and TS are terrible, I write everything in Assembly

2023-09-06 20:30 UTC, tbo approved these changes

2023-09-06 20:30 UTC, joseywoermann approved these changes

2023-09-06 20:31 UTC, jorgeruvalcaba commented
LGTM!

2023-09-06 20:31 UTC, ahmedwaleedmalik approved these changes

2023-09-06 20:31 UTC, GorlikItsMe approved these changes

2023-09-06 20:32 UTC, fracek approved these changes

2023-09-06 20:32 UTC, brookesb91 approved these changes

2023-09-06 20:33 UTC, neolectron commented
Are you a contributor or something ?

2023-09-06 20:34 UTC, michaelbayday approved these changes

2023-09-06 20:34 UTC, leonakao approved these changes

2023-09-06 20:34 UTC, jwandekoken approved these changes

2023-09-06 20:35 UTC, henrycunh commented
> > > > what is lgtm??
> > > 
> > > 
> > > Looks good to me
> > 
> > 
> > wrong
> 
> So, what is the correct?
> 
> I researched and found that. https://www.unosquare.com/blog/what-does-lgtm-mean-in-github-code-reviews/#:~:text=The%20letters%20LGTM%20stand%20for,use%20it%20after%20reviewing%20code.


research better
<img width="671" alt="image" src="https://github.com/hotwired/turbo/assets/8951736/3c1c0075-97bb-4b5c-bfce-f3ddb64ec7a2">

2023-09-06 20:35 UTC, Nahrin-Malakes commented
LGTM

2023-09-06 20:35 UTC, Nsttt commented
LGMT

2023-09-06 20:36 UTC, sarjann commented
LGTM

2023-09-06 20:36 UTC, filipkania approved these changes

2023-09-06 20:38 UTC, SyedMSawaid approved these changes

2023-09-06 20:39 UTC, Nsttt approved these changes

2023-09-06 20:40 UTC, gitgudchannel commented
BASED AND TYPEPILLED

2023-09-06 20:40 UTC, GJSBRT approved these changes
lgtm

2023-09-06 20:40 UTC, Arrow7000 approved these changes

2023-09-06 20:40 UTC, gitgudchannel approved these changes

2023-09-06 20:42 UTC, MaximMaximS approved these changes
LGTM

2023-09-06 20:43 UTC, alicanerdogan commented
Ship it.

2023-09-06 20:43 UTC, Ekkana approved these changes

2023-09-06 20:43 UTC, Ph4seOn3 commented
Easy Merge

2023-09-06 20:44 UTC, boredland approved these changes

2023-09-06 20:44 UTC, THernandez03 commented
LGTM

2023-09-06 20:44 UTC, alex289 approved these changes

2023-09-06 20:44 UTC, THernandez03 approved these changes
LGTM

2023-09-06 20:44 UTC, consvic approved these changes

2023-09-06 20:44 UTC, cvoges12 commented
LGTM

2023-09-06 20:45 UTC, 223230 commented
LGTM 💪💪💪

2023-09-06 20:45 UTC, matiduda commented
LGTM 👌

2023-09-06 20:46 UTC, matiduda approved these changes

2023-09-06 20:46 UTC, Abdullah-l approved these changes
LGTM ✅

2023-09-06 20:46 UTC, pedrodurek approved these changes

2023-09-06 20:47 UTC, esbanarango commented
LTGM 🤝 ✅

2023-09-06 20:47 UTC, esbanarango approved these changes

2023-09-06 20:48 UTC, lonelyteapot commented
lgtm

2023-09-06 20:50 UTC, cvoges12 approved these changes

2023-09-06 20:50 UTC, JezerM approved these changes

2023-09-06 20:50 UTC, aminya approved these changes

2023-09-06 20:51 UTC, laurencetaylor approved these changes

2023-09-06 20:51 UTC, gerzonc approved these changes
LGTM

2023-09-06 20:51 UTC, markcerqueira approved these changes
Wow - this is a game-changer!!!!!!

2023-09-06 20:52 UTC, nicknytko approved these changes

2023-09-06 20:53 UTC, shahzad31 approved these changes

2023-09-06 20:53 UTC, klenovich approved these changes

2023-09-06 20:53 UTC, fenixburnaby approved these changes

2023-09-06 20:57 UTC, neo-franklin-tina commented
Lol, drama king.

2023-09-06 20:57 UTC, gabrielnafuzi approved these changes
LGTM!

2023-09-06 20:57 UTC, alexismellamo commented
LGTM

2023-09-06 20:57 UTC, alexismellamo approved these changes

2023-09-06 20:57 UTC, lucasmontano commented
don't be a coward go typeless

2023-09-06 21:00 UTC, nickwelsh commented
LGTM 💯👍

2023-09-06 21:00 UTC, nezdemkovski approved these changes

2023-09-06 21:01 UTC, BenaCamelas approved these changes

2023-09-06 21:02 UTC, cherryramatisdev commented
LGTM

2023-09-06 21:04 UTC, ArthurDias01 commented
LTGM 🤝 ✅

2023-09-06 21:05 UTC, MashhoodIjaz approved these changes
LGTM 👍

2023-09-06 21:05 UTC, Mich-River approved these changes

2023-09-06 21:05 UTC, Mich-River commented
lgtm

2023-09-06 21:06 UTC, murindwaz commented
LGTM 😂

2023-09-06 21:06 UTC, Alex775 commented
LGTM

2023-09-06 21:07 UTC, fobos531 approved these changes

2023-09-06 21:07 UTC, JWo1F approved these changes

2023-09-06 21:07 UTC, ngbamaw commented
LGTM

2023-09-06 21:09 UTC, fadamakis requested changes
Please add unit tests.

2023-09-06 21:09 UTC, aidan-casey approved these changes

2023-09-06 21:09 UTC, Luismi74 approved these changes
LGTM Too!

2023-09-06 21:09 UTC, alexove-hck approved these changes

2023-09-06 21:11 UTC, alexove-hck approved these changes

2023-09-06 21:11 UTC, alexove-hck commented
L REALLY GTM

2023-09-06 21:11 UTC, lilbyteltd approved these changes

2023-09-06 21:12 UTC, ceIia approved these changes

2023-09-06 21:12 UTC, collin approved these changes

2023-09-06 21:13 UTC, pankofufu commented
LGTM i think we will benefit from strong typing

2023-09-06 21:17 UTC, samialdury approved these changes

2023-09-06 21:18 UTC, jakubczarnowski approved these changes

2023-09-06 21:20 UTC, migueldaipre commented
LGTM

2023-09-06 21:22 UTC, Delta456 approved these changes

2023-09-06 21:23 UTC, vieirin approved these changes
LGTM

2023-09-06 21:24 UTC, hood commented
lgtm

2023-09-06 21:24 UTC, pailhead commented
LGTM

2023-09-06 21:26 UTC, seahindeniz approved these changes

2023-09-06 21:28 UTC, Jose4gg commented
LGTM

2023-09-06 21:28 UTC, zisra reviewed
LGTM

2023-09-06 21:28 UTC, milovangudelj commented
LGTM

2023-09-06 21:29 UTC, KaulSe approved these changes
LGTM! perfect PR

2023-09-06 21:29 UTC, Chavao approved these changes

2023-09-06 21:30 UTC, andrewdoro commented
SBFB So big f**** balls

2023-09-06 21:31 UTC, andrewdoro approved these changes

2023-09-06 21:32 UTC, allamgr approved these changes
LGTM

2023-09-06 21:33 UTC, thereis commented
LGTM, approve now!

2023-09-06 21:33 UTC, migueldaipre approved these changes

2023-09-06 21:33 UTC, thereis approved these changes

2023-09-06 21:34 UTC, Fry98 reviewed
This PR, created just 6 hours after TypeScript got removed, seems very rushed.

This PR fundamentally changes the library. It changes the library's main language. I don't see the need to rush this? Why was this rushed?

Was there any prior discussion on this change?

This is an open-source library, not just source available.
There are many other open-source libraries using this library directly or indirectly.

And making this important change rushed, ignoring ALL (and I mean ALL) of the PR comments...sets a precedent.

Is this how [ping.gg](https://ping.gg/) will be developed as well? On a one man's whim?
Why do we always have to have these arguments? What was so difficult to ask the community (including maintainers), have a constructive discussion, and come up with an agreement whether or not to switch from JS to TS? Or do we just wait for @t3dotgg to make a PR and then we'll just merge whatever was written there.

You could've better used your time removing TypeScript from other popular libraries.

2023-09-06 21:34 UTC, Fry98 commented on src/core/drive/error_renderer.ts
> +  static renderElement(currentElement: HTMLBodyElement, newElement: HTMLBodyElement) {
We added unnecessary information here. It should be left to the developer to figure out they can only pass in a `<body>` element into `currentElement` and `newElement` in order to maximize their engagement while writing code. I suggest changing this to `currentElement: HTMLElement, newElement: HTMLElement`.

2023-09-06 21:34 UTC, Fry98 commented on src/core/drive/form_submission.ts
> +      detail: { formSubmission: this, ...this.result },
Why was the formatting style changed in this PR? This seems irrelevant.

2023-09-06 21:34 UTC, Fry98 commented on src/core/drive/form_submission.ts
> +function buildFormData(formElement: HTMLFormElement, submitter?: HTMLElement): FormData {
It might be funnier to NOT know that `submitter` is an optional argument here.

2023-09-06 21:34 UTC, Fry98 commented on src/core/drive/head_snapshot.ts
> +    }, undefined as Element | undefined)
Not sure why you fixed this bug. We were keeping it on purpose so we could fix it later and then pretend like we did some actual work. Change it to `(undefined | undefined) as Element | undefined` to preserve it.

2023-09-06 21:34 UTC, Fry98 commented on src/tests/functional/form_mode_tests.ts
> +async function gotoPageWithFormMode(page: Page, formMode: "on" | "off" | "optin") {
Would be great to leave this as just `formMode: string`. If you want to contribute to this project you should put in the work figuring out what that actual options are yourself.

2023-09-06 21:35 UTC, AnnaGottin commented
LGTM

2023-09-06 21:37 UTC, Zeko369 approved these changes

2023-09-06 21:38 UTC, AndKenneth approved these changes
lgtm

2023-09-06 21:46 UTC, akxcix approved these changes
LGTM

2023-09-06 21:46 UTC, mattkauffman23 commented
few nits but otherwise LGTM. Ship it

2023-09-06 21:47 UTC, koladev32 commented
LGTM!

2023-09-06 21:51 UTC, advany commented
LGTM!

2023-09-06 21:52 UTC, advany approved these changes

2023-09-06 21:53 UTC, ryoung approved these changes

2023-09-06 21:55 UTC, Cyber-Ware approved these changes

2023-09-06 21:58 UTC, ghengeveld approved these changes

2023-09-06 21:58 UTC, GSTJ approved these changes
🚢

2023-09-06 22:01 UTC, pstevovski approved these changes

2023-09-06 22:03 UTC, ndianabasi approved these changes

2023-09-06 22:06 UTC, alii commented
merg! 🕺

2023-09-06 22:06 UTC, alii approved these changes

2023-09-06 22:07 UTC, BrendanSluke commented
LGTM

2023-09-06 22:07 UTC, dreyfus92 approved these changes
Ship it 🚀

2023-09-06 22:08 UTC, BrendanSluke approved these changes

2023-09-06 22:09 UTC, ShukantPal approved these changes

2023-09-06 22:12 UTC, matthewwilson approved these changes

2023-09-06 22:13 UTC, ooliver1 reviewed
Pointed out an issue @Fry98 missed. TypeScript finding bugs before running is too advanced for this project.

Huh, my comment disappeared, I was referring to `null`s now being explicit again and how the developer should expect the unexpected instead.

2023-09-06 22:14 UTC, elektronik2k5 approved these changes

2023-09-06 22:17 UTC, danielhusar approved these changes

2023-09-06 22:18 UTC, shellscape commented
![](https://media.tenor.com/X613sHzCXL8AAAAC/nerds-shouts.gif?t=AAYEuBVIf1MB_04G0QuE1g&c=VjFfdHdpdHRlcg)

2023-09-06 22:18 UTC, ShukantPal commented
Fully recognize that JavaScript offers some people some advantages, but to my eyes, the benefits are evident in this PR. The code not only reads much better, it's also freed of the `TypeError: whatToSay is not declared` and mental gymnastics needed to guess what the original JavaScript authors meant when they wrote the original code.

We write all our client side code at ping.gg now in pure TypeScript and the same too with any internal libraries. This is going to bring that in line.

All the love and appreciation to contributors who would prefer JavaScript. This is one of those debates where arguments aren't likely to move anyone's fundamental position, so I won't attempt to do that.

2023-09-06 22:18 UTC, mkayander commented
LGTM

2023-09-06 22:22 UTC, ssilve1989 approved these changes

2023-09-06 22:23 UTC, sacummings91 commented
LGTM

2023-09-06 22:25 UTC, Jordan-Hall requested changes
Typescript  can be useful, especially using latest features before browser support. However, browsers and runtime engines as a whole has vastly improved. Typescript doesn't offer the same benefits as other real strongly typed language. The debate is pointless, js docs can.offer just as good of a solution for when something is important.

Lastly, Typescript can cause additional bugs where thays not true and extremely slow to complie delaying emergency fixes. If you wish to use Typescript then fork the project or just maintain a active type definition. Problem solve. Long live fast deployment and code as is.

2023-09-06 22:25 UTC, balazsotakomaiya approved these changes

2023-09-06 22:29 UTC, charlie632 approved these changes

2023-09-06 22:31 UTC, Fry98 commented
> Pointed out an issue @Fry98 missed. TypeScript finding bugs before running is too advanced for this project.

While that is a valid concern, DO keep in mind that TypeScript also gives us the ability to type stuff incorrectly, thus guiding contributors towards creating entirely new bugs that might otherwise never occour in a simple JS codebase where there are no misleading type definitions ready to stab you in the back.

2023-09-06 22:31 UTC, pyk approved these changes
LGTM

2023-09-06 22:31 UTC, EijunnN commented
Nice

2023-09-06 22:33 UTC, shaunburch approved these changes

2023-09-06 22:36 UTC, Adonsio approved these changes
LGTM✅

2023-09-06 22:36 UTC, Punie approved these changes

2023-09-06 22:36 UTC, clawrence121 approved these changes

2023-09-06 22:47 UTC, godoyLeonardo approved these changes

2023-09-06 22:47 UTC, yura2100 approved these changes
🚀🚀🚀

2023-09-06 22:50 UTC, colbysadams approved these changes

2023-09-06 22:51 UTC, dlo approved these changes

2023-09-06 22:52 UTC, schoblaska approved these changes

2023-09-06 22:52 UTC, pro4tlzz commented
LGTM 🚀

2023-09-06 23:03 UTC, joao-conde commented
LGTM

2023-09-06 23:03 UTC, Rattlyy approved these changes
LGTM

2023-09-06 23:07 UTC, Nathanw approved these changes

2023-09-06 23:08 UTC, nusendra commented
LGTM !!!!

2023-09-06 23:12 UTC, GentryRiggen approved these changes
LGTM

2023-09-06 23:12 UTC, wizardfiction approved these changes

2023-09-06 23:14 UTC, citypaul commented
Looks ok, but nitpick: have you considered converting the entire codebase to php?

2023-09-06 23:20 UTC, cnrmurphy approved these changes
Adding TypeScript is kind of a wild idea, but I think it might be worth it. LGTM

2023-09-06 23:23 UTC, citypaul approved these changes
Solid 5/7

2023-09-06 23:29 UTC, arthurfiorette commented
I know we should stop spamming this issue, but one last thing we should consider is how typescript offers "built in" documentation, clear or unclear, to other developers. For such a project as this one, it would actually be helpful.

2023-09-06 23:45 UTC, EarliestFall988 commented
LGTM

2023-09-06 23:45 UTC, losh11 commented
looks bad to me

2023-09-07 00:00 UTC, iwdt commented
LGTM

2023-09-07 00:07 UTC, joseangel-sc approved these changes
LGTM, let's go!

2023-09-07 00:12 UTC, Wyatt-SG approved these changes

2023-09-07 00:13 UTC, mathysIN approved these changes

2023-09-07 00:18 UTC, AdrianDeAnda approved these changes

2023-09-07 00:18 UTC, natedunn commented
Yep, good to merge. Thanks.

2023-09-07 00:20 UTC, patrickmccallum approved these changes

2023-09-07 00:26 UTC, codingki approved these changes

2023-09-07 00:29 UTC, WagnerMoreira approved these changes
LGTM :)

2023-09-07 00:43 UTC, jmz7v approved these changes

2023-09-07 00:44 UTC, carlos-rodrigo approved these changes

2023-09-07 00:45 UTC, tebuevd approved these changes
lgtm

2023-09-07 00:51 UTC, breqdev commented
🔥🔥🔥

2023-09-07 00:52 UTC, breqdev approved these changes

2023-09-07 00:56 UTC, dcheng1290 approved these changes

2023-09-07 00:59 UTC, forresthopkinsa approved these changes

2023-09-07 01:11 UTC, KisaragiEffective approved these changes

2023-09-07 01:11 UTC, ImBIOS approved these changes
Looks Perfect To Me

2023-09-07 01:15 UTC, Luigi123 approved these changes

2023-09-07 01:19 UTC, timbuckley approved these changes
lgtm, should improve DX greatly.

2023-09-07 01:21 UTC, denniscampos approved these changes

2023-09-07 01:21 UTC, ryanyogan commented
When your at work and ask if anyone can review your PR... and everyone is too busy reviewing this 🤣🤣🚀

2023-09-07 01:27 UTC, jclusso requested changes
Seems bloated.

2023-09-07 01:28 UTC, AZagatti approved these changes
LGTM

2023-09-07 01:30 UTC, park012241 approved these changes

2023-09-07 01:42 UTC, Claudemirovsky approved these changes
LGTM

2023-09-07 01:43 UTC, janfranco27 approved these changes

2023-09-07 01:45 UTC, janklimo commented
Ship it 🚢

2023-09-07 01:45 UTC, eldyvoon commented
Lgtm, pls merge

2023-09-07 01:46 UTC, bvoo approved these changes

2023-09-07 01:46 UTC, eldyvoon approved these changes

2023-09-07 01:51 UTC, hansderly commented
LGTM

2023-09-07 02:22 UTC, kayode0x approved these changes

2023-09-07 02:23 UTC, chrissnyder commented
this pr already has been discussed 3x as long as #971. too much discussion, should just merge

2023-09-07 02:25 UTC, jdforsythe commented
Burn. LGTM

2023-09-07 02:28 UTC, jpike88 commented
This PR is taking too long to merge, something as simple and inconsequential as this should have been merged in a couple of hours, tops!

2023-09-07 02:29 UTC, anantsimran approved these changes
For 🍿

2023-09-07 02:34 UTC, junaga commented
@t3dotgg you know that `jsconfig.json` > `tsconfig.json` yet you make a show. is this why no one respects you? take a look at @fireship, he's a responsible creator.

2023-09-07 02:34 UTC, airowe approved these changes

2023-09-07 02:35 UTC, narze approved these changes
Quite surprising that #971 has no JSDocs in it, that's really bad for DX

2023-09-07 02:38 UTC, SwooshyCueb approved these changes

2023-09-07 02:40 UTC, thammarith approved these changes
LGTM

2023-09-07 02:43 UTC, vsylvestre approved these changes

2023-09-07 02:46 UTC, NexonTreeHouse approved these changes

2023-09-07 02:47 UTC, Greek commented
lgtm

2023-09-07 02:47 UTC, Greek approved these changes

2023-09-07 02:50 UTC, ven approved these changes

2023-09-07 02:50 UTC, joshmanders commented
Remember, this guys only contribution to anything of substance was putting together a shoddy next.js boilerplate using trpc's readme, then actual competent devs came in and built a real DX around it while he throws himself into as much drama and "Don't forget about wittle me in your debate on the merits of JS vs TS" to stroke his own narcissistic ego and to promote his shitty YouTube videos where he struggles to draw diagrams on Excalidraw for 45 minutes while he talks about scaling his 17 user "startup" app.

Theo, do us all a favor and leave real devs alone to do their thing. You had ZERO issues with Rich Harris removing TypeScript from Svelte, but now that 37Signals did it here, it's an issue? Double standard much?

2023-09-07 02:50 UTC, pythongiant approved these changes
LGTM 👍

2023-09-07 02:51 UTC, apiel51 approved these changes

2023-09-07 02:54 UTC, superhooman approved these changes

2023-09-07 03:00 UTC, TechStudent10 commented
LGTM of course Theo is on it haha

2023-09-07 03:01 UTC, ThePrimeagen commented
Not gonna be active on Github reviewing typescript PRs tonight. I’m meeting a girl (a real one) in half an hour (wouldn’t expect a lot of you to understand anyway) so please don’t DM me asking me where I am (im with the girl, ok) you’ll most likely get aired because ill be with the girl (again I don’t expect you to understand) shes actually really interested in me and its not a situation i can pass up for some meaningless Github JavaScript degenerates (because ill be meeting a girl, not that you really are going to understand) this is my life now. Meeting women and not wasting my precious time online, I have to move on from such simple things and branch out (you wouldnt understand)

2023-09-07 03:08 UTC, closed without merging

2023-09-07 03:08 UTC, tyhuber1 approved these changes